### ISSUE TITLE
Does not build on OS X Sierra 10.12.3

### ISSUE THREAD

**Issue by JamesDunne** [cjd/mtpfs#16]
Installed latest OSX Fuse 3.5.8 from https://osxfuse.github.io/
Installed mtpfs dependencies via:
```
brew install libid3tag
brew install libmad
brew install libmtp
```

After `./configure` and `make` I get these errors:
```In file included from mtpfs.c:9:
In file included from ./mtpfs.h:13:
In file included from /usr/local/include/osxfuse/fuse/fuse.h:31:
/usr/local/include/osxfuse/fuse/fuse_common.h:555:8: error: On Darwin API version 25 or greater must be used
#            error On Darwin API version 25 or greater must be used
             ^
In file included from mtpfs.c:9:
./mtpfs.h:20:10: fatal error: 'sys/statfs.h' file not found
#include <sys/statfs.h>
         ^
2 errors generated.
```

**Comment by benseven** [comment]
Same here, though not limited to Sierra; I'm on OS 10.11.5
